/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CompatibilityRouteImport } from './routes/compatibility'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as BuilderRouteImport } from './routes/builder'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileIndexRouteImport } from './routes/profile.index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ProfileWishlistRouteImport } from './routes/profile.wishlist'
import { Route as ProfileOrdersRouteImport } from './routes/profile.orders'
import { Route as ProfileBuildsRouteImport } from './routes/profile.builds'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminProductsRouteImport } from './routes/admin/products'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CompatibilityRoute = CompatibilityRouteImport.update({
  id: '/compatibility',
  path: '/compatibility',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderRoute = BuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfileRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProfileWishlistRoute = ProfileWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileOrdersRoute = ProfileOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileBuildsRoute = ProfileBuildsRouteImport.update({
  id: '/builds',
  path: '/builds',
  getParentRoute: () => ProfileRoute,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProductsRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/builder': typeof BuilderRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/compatibility': typeof CompatibilityRoute
  '/login': typeof LoginRoute
  '/products': typeof ProductsRouteWithChildren
  '/profile': typeof ProfileRouteWithChildren
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/users': typeof AdminUsersRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/profile/builds': typeof ProfileBuildsRoute
  '/profile/orders': typeof ProfileOrdersRoute
  '/profile/wishlist': typeof ProfileWishlistRoute
  '/admin/': typeof AdminIndexRoute
  '/profile/': typeof ProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/builder': typeof BuilderRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/compatibility': typeof CompatibilityRoute
  '/login': typeof LoginRoute
  '/products': typeof ProductsRouteWithChildren
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/users': typeof AdminUsersRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/profile/builds': typeof ProfileBuildsRoute
  '/profile/orders': typeof ProfileOrdersRoute
  '/profile/wishlist': typeof ProfileWishlistRoute
  '/admin': typeof AdminIndexRoute
  '/profile': typeof ProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/builder': typeof BuilderRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/compatibility': typeof CompatibilityRoute
  '/login': typeof LoginRoute
  '/products': typeof ProductsRouteWithChildren
  '/profile': typeof ProfileRouteWithChildren
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/users': typeof AdminUsersRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/profile/builds': typeof ProfileBuildsRoute
  '/profile/orders': typeof ProfileOrdersRoute
  '/profile/wishlist': typeof ProfileWishlistRoute
  '/admin/': typeof AdminIndexRoute
  '/profile/': typeof ProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/builder'
    | '/cart'
    | '/checkout'
    | '/compatibility'
    | '/login'
    | '/products'
    | '/profile'
    | '/register'
    | '/search'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/users'
    | '/products/$slug'
    | '/profile/builds'
    | '/profile/orders'
    | '/profile/wishlist'
    | '/admin/'
    | '/profile/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/builder'
    | '/cart'
    | '/checkout'
    | '/compatibility'
    | '/login'
    | '/products'
    | '/register'
    | '/search'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/users'
    | '/products/$slug'
    | '/profile/builds'
    | '/profile/orders'
    | '/profile/wishlist'
    | '/admin'
    | '/profile'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/builder'
    | '/cart'
    | '/checkout'
    | '/compatibility'
    | '/login'
    | '/products'
    | '/profile'
    | '/register'
    | '/search'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/users'
    | '/products/$slug'
    | '/profile/builds'
    | '/profile/orders'
    | '/profile/wishlist'
    | '/admin/'
    | '/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BuilderRoute: typeof BuilderRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  CompatibilityRoute: typeof CompatibilityRoute
  LoginRoute: typeof LoginRoute
  ProductsRoute: typeof ProductsRouteWithChildren
  ProfileRoute: typeof ProfileRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  SearchRoute: typeof SearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compatibility': {
      id: '/compatibility'
      path: '/compatibility'
      fullPath: '/compatibility'
      preLoaderRoute: typeof CompatibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder': {
      id: '/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof BuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/profile/wishlist': {
      id: '/profile/wishlist'
      path: '/wishlist'
      fullPath: '/profile/wishlist'
      preLoaderRoute: typeof ProfileWishlistRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/orders': {
      id: '/profile/orders'
      path: '/orders'
      fullPath: '/profile/orders'
      preLoaderRoute: typeof ProfileOrdersRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/builds': {
      id: '/profile/builds'
      path: '/builds'
      fullPath: '/profile/builds'
      preLoaderRoute: typeof ProfileBuildsRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ProductsRouteChildren {
  ProductsSlugRoute: typeof ProductsSlugRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsSlugRoute: ProductsSlugRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

interface ProfileRouteChildren {
  ProfileBuildsRoute: typeof ProfileBuildsRoute
  ProfileOrdersRoute: typeof ProfileOrdersRoute
  ProfileWishlistRoute: typeof ProfileWishlistRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileBuildsRoute: ProfileBuildsRoute,
  ProfileOrdersRoute: ProfileOrdersRoute,
  ProfileWishlistRoute: ProfileWishlistRoute,
  ProfileIndexRoute: ProfileIndexRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BuilderRoute: BuilderRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  CompatibilityRoute: CompatibilityRoute,
  LoginRoute: LoginRoute,
  ProductsRoute: ProductsRouteWithChildren,
  ProfileRoute: ProfileRouteWithChildren,
  RegisterRoute: RegisterRoute,
  SearchRoute: SearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
